version: "2.1"
services:
  grafana:
    image: ${grafana_image}
    container_name: git_grafana
    hostname: grafana
    restart: always
    env_file:
      - grafana.env
    ports:
      - "82:3000/tcp"
    volumes:
      - "./grafana/usr/share/grafana/conf:/usr/share/grafana/conf"
      - "./grafana/usr/share/grafana/data:/usr/share/grafana/data"
    links: 
      - influx:influxdb
      - grafana_mariadb:grafana_mariadb
      - grafana_renderer:grafana_renderer
    networks:
      network_1:
        ipv4_address: 10.6.0.2
  influx:
    image: ${influx_image}
    container_name: git_influx
    hostname: influx
    restart: always
    ports:
      - "8086:8086/tcp"
    volumes:
      - "./influx/etc/influxdb:/etc/influxdb"
      - "./influx/var/lib/influxdb:/var/lib/influxdb"
    networks:
      network_1:
        ipv4_address: 10.6.0.3
  telegraf:
    image: ${telegraf_image}
    container_name: git_telegraf
    hostname: docker-telegraf
    restart: always
    volumes:
      - "./telegraf/etc/telegraf:/etc/telegraf"
    links: 
      - influx:influxdb
    networks:
      network_1:
        ipv4_address: 10.6.0.4
  grafana_mariadb:
    image: ${mariadb_image}
    container_name: git_grafana_mariadb
    hostname: mariadb
    restart: always
    volumes:
      - "./mariadb/etc/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf"
      - "./mariadb/etc/mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d"
      - "./mariadb/var/lib/mysql:/var/lib/mysql"
    networks:
      network_1:
        ipv4_address: 10.6.0.5
  grafana_renderer:
    image: grafana/grafana-image-renderer:2.0.0
    container_name: git_grafana_renderer
    hostname: renderer
    restart: always
    networks:
      network_1:
        ipv4_address: 10.6.0.6
        
networks:
  network_1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "monitor0"
    ipam:
      driver: default
      config:
      - subnet: 10.6.0.0/28
        gateway: 10.6.0.1
